### ISSUE TITLE
Selenium is detectable

### ISSUE THREAD

**Issue by diederik222** [tmb5cg/Fifa21-Autobidder#23]
Hey,

Nice script you made here man. Just as a warning for everyone that wants to try this out: It is possible to detect it when you are using Selenium in combination with the (chrome) webdriver. I have worked with Selenium a lot to scrape websites and I do sometimes get banned for using it. It's actually pretty easy to see if someone uses the chromedriver.exe. There is a way to bypass this though, but even then I think there are ways to be detected and obviously get banned from the fifa market (or worse): 

https://stackoverflow.com/questions/33225947/can-a-website-detect-when-you-are-using-selenium-with-chromedriver/41220267

**Comment by Y0lan** [comment]
You can run this on every folder with chromedriver in it
`perl -pi -e 's/cdc_/xxx_/g' chromedriver`

it will limit the detection possibility.

**Comment by tmb5cg** [comment]
yep this is all correct - need to update the readme. I do believe it is less dangerous than direct JS injection since in theory you could be running chromedriver scripts for work/other things. To be honest I don't think EA really goes against the little fish unless you are reckless, just the people making absurd amounts with farms
