### ISSUE TITLE
Config.json error

### ISSUE THREAD

**Issue by Hughesy** [tmb5cg/Fifa21-Autobidder#4]
Hi there, went to run the project, but i keep getting a config.json error as seen in the image below. Any ideas how to fix this? Thanks[
<img width="679" alt="Screenshot 2021-03-08 at 09 51 55" src="https://user-images.githubusercontent.com/2457878/110304977-1a9a4e00-7ff4-11eb-8246-d27ef85ad8e6.png">
](url)

**Comment by tmb5cg** [comment]
Ah my bad. The gitignore didn't upload the file - I will push an update now. Thanks for letting me know!

**Comment by tmb5cg** [comment]
Just pushed an update - let me know if it works! 

Also the transfer list managing function has been causing issues so let me know if that stops working too

**Comment by Hughesy** [comment]
Is there a way to stop the bot once it has started?

**Comment by tmb5cg** [comment]
This is what I'm currently working on, currently if you manually intervene it should realize and stop itself. 

The issue is I haven't built a way for it to remember where it was, so the only way to restart is to hit the Start button again. Which then creates a new Autobidder object and if forgets all the previous stats (like bids made etc)

I tried to make sure it never gets stuck in an infinite loop anywhere but haven't had time to thoroughly test. Ideally your transfer list and watch list should be empty before starting it, it doesn't handle unknown players (players not on its buy list) correctly (yet)

Keep me posted with any errors

**Comment by tmb5cg** [comment]
Basically I just need to add a Pause button but it's not as simple as it seems since the bot runs on a separate thread from the GUI if that makes sense. Threads are confusing so I have to read up on how to do this

**Comment by Hughesy** [comment]
> Basically I just need to add a Pause button but it's not as simple as it seems since the bot runs on a separate thread from the GUI if that makes sense. Threads are confusing so I have to read up on how to do this

I'll start a new thread when I find new issues.

I have just started a new one
