### ISSUE TITLE
Logs lag and stop to record.

### ISSUE THREAD

**Issue by zetteron** [tmb5cg/Fifa21-Autobidder#6]
then 1 itteration of program finishes and it doesnt start bidding again.
![image](https://user-images.githubusercontent.com/48014790/111899913-9490f500-8a40-11eb-81e6-539a289cac4f.png)

i'm not a great programmer, so i cant figure out whats wrong, sorry if the issue is my stupidity

**Comment by tmb5cg** [comment]
It only works on base cards! Make sure to read the dialogue alert messages they are important, unexpected stuff can happen!

I'm pushing a big update today which should fix a bunch of bugs. But your issue here is bc it isn't built for anything but gold cards sry

**Comment by tmb5cg** [comment]
Sorry that's not a great answer - the reason it only works on base cards is because there isn't a publicly updates full player database. 

So it's as if the bot only knows players that existed on October 1st when the game came out

When the bot tries to find that in forms players ID (based on rating and card name), it returns 0, and if the ID is zero the bot freezes (since weird stuff can happen)

**Comment by zetteron** [comment]
but all i had here are completely normal gold cards, thats the thing. I know i lack information, but I read carefully and added only gold normal non-informs. From now on i'll check data folder and get players from there.

**Comment by tmb5cg** [comment]
Any luck? I pushed a new update and it seems to be working well
